# pull official base image
FROM node:16


# set working directory
WORKDIR /client
# add `/app/node_modules/.bin` to $PATH
ENV PATH /client/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json ./
RUN npm install -g npm@latest
RUN mkdir -p /client/node_modules/.cache && chown -R node /client/node_modules/.cache 
RUN npm install react-scripts@5.0.1
RUN npm install


# add app
COPY --chown=node:node . ./
USER node


# start app
CMD ["npm", "start"]